language: python
sudo: false
install: pip install tox
script: tox
env:
  - TOXENV=py27-django16-drf31
  - TOXENV=py27-django16-drf32
  - TOXENV=py32-django16-drf31
  - TOXENV=py32-django16-drf32
  - TOXENV=py33-django16-drf31
  - TOXENV=py33-django16-drf32
  - TOXENV=py27-django17-drf31
  - TOXENV=py27-django17-drf32
  - TOXENV=py32-django17-drf31
  - TOXENV=py32-django17-drf32
  - TOXENV=py33-django17-drf31
  - TOXENV=py33-django17-drf32
  - TOXENV=py34-django17-drf31
  - TOXENV=py34-django17-drf32
  - TOXENV=py27-django18-drf31
  - TOXENV=py27-django18-drf32
  - TOXENV=py32-django18-drf31
  - TOXENV=py32-django18-drf32
  - TOXENV=py33-django18-drf31
  - TOXENV=py33-django18-drf32
  - TOXENV=py34-django18-drf31
  - TOXENV=py34-django18-drf32
  - TOXENV=py27-django19-drf31
  - TOXENV=py27-django19-drf32
  - TOXENV=py34-django19-drf31
  - TOXENV=py34-django19-drf32
